import React, { useEffect, useState } from 'react';
import { useNavigate } from 'react-router-dom';

const API_BASE = import.meta.env.VITE_API_URL || '';
const fontFamily = '-apple-system, BlinkMacSystemFont, "SF Pro Text", "Segoe UI", Roboto, Helvetica, Arial, sans-serif';
const serif = 'ui-serif, Georgia, Cambria, "Times New Roman", Times, serif';

const shellStyle = {
  backgroundColor: '#0F0F10',
  color: '#EBEBF5',
  fontFamily,
  WebkitFontSmoothing: 'antialiased',
  minHeight: '100vh',
  width: '100vw',
};

const containerStyle = {
  maxWidth: '960px',
  margin: '0 auto',
  padding: '32px 28px 80px',
};

const DemoList = () => {
  const navigate = useNavigate();
  const [demos, setDemos] = useState([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState(null);

  useEffect(() => {
    let mounted = true;
    (async () => {
      try {
        const res = await fetch(`${API_BASE}/api/demo`);
        if (!res.ok) throw new Error(`Server returned ${res.status}`);
        const j = await res.json();
        if (mounted) {
          setDemos(j.demos || []);
          setLoading(false);
        }
      } catch (e) {
        if (mounted) {
          setError(e.message || String(e));
          setLoading(false);
        }
      }
    })();
    return () => { mounted = false; };
  }, []);

  return (
    <div style={shellStyle}>
      <TopBar onExit={() => navigate('/')} onStart={() => navigate('/start')} />
      <div style={containerStyle}>
        <div style={{ marginBottom: '36px' }}>
          <div style={{
            fontSize: '11px', textTransform: 'uppercase', letterSpacing: '1.8px',
            fontWeight: 700, color: '#0A84FF', marginBottom: '14px',
          }}>
            Demo Briefs
          </div>
          <h1 style={{
            fontFamily: serif, fontSize: 'clamp(28px, 4vw, 40px)',
            fontWeight: 500, letterSpacing: '-0.8px', color: '#EBEBF5',
            lineHeight: 1.15, marginBottom: '14px',
          }}>
            See what a Courtless brief looks like.
          </h1>
          <div style={{
            fontSize: '15px', color: 'rgba(235, 235, 245, 0.68)',
            lineHeight: 1.65, maxWidth: '680px',
          }}>
            These are example briefs generated by Courtless for sample disputes. Real audits
            use your own documents and circumstances — click through any of these to see the
            format, depth, and tone.
          </div>
        </div>

        {loading && (
          <div style={{ padding: '80px 0', textAlign: 'center', color: 'rgba(235, 235, 245, 0.6)' }}>
            Loading demo briefs…
          </div>
        )}
        {error && (
          <div style={{
            padding: '20px 24px', backgroundColor: 'rgba(255, 69, 58, 0.06)',
            border: '1px solid rgba(255, 69, 58, 0.25)', borderRadius: '10px',
            color: '#FF6B5C', fontSize: '13px',
          }}>
            Couldn't load demos — {error}.
          </div>
        )}

        {!loading && !error && (
          <div style={{
            display: 'grid',
            gridTemplateColumns: 'repeat(auto-fit, minmax(280px, 1fr))',
            gap: '16px',
          }}>
            {demos.map(d => (
              <DemoCard
                key={d.id}
                demo={d}
                onOpen={() => navigate(`/demo/${d.id}`)}
              />
            ))}
          </div>
        )}

        <div style={{
          marginTop: '48px', padding: '24px 26px',
          backgroundColor: '#131314',
          border: '1px solid rgba(235, 235, 245, 0.06)',
          borderRadius: '12px',
          display: 'flex', justifyContent: 'space-between', alignItems: 'center',
          flexWrap: 'wrap', gap: '16px',
        }}>
          <div style={{ fontSize: '14px', color: 'rgba(235, 235, 245, 0.72)', maxWidth: '540px', lineHeight: 1.55 }}>
            Ready to run your own? Upload your documents and we'll draft your brief in about a minute.
          </div>
          <button
            onClick={() => navigate('/start')}
            style={{
              padding: '12px 22px', borderRadius: '8px',
              backgroundColor: '#0A84FF', color: 'white', border: 'none',
              fontSize: '14px', fontWeight: 600, fontFamily, cursor: 'pointer',
            }}
          >
            Start my audit →
          </button>
        </div>
      </div>
    </div>
  );
};

const DemoCard = ({ demo, onOpen }) => {
  const [hover, setHover] = useState(false);
  return (
    <button
      onClick={onOpen}
      onMouseEnter={() => setHover(true)}
      onMouseLeave={() => setHover(false)}
      style={{
        textAlign: 'left',
        backgroundColor: hover ? '#1E1E20' : '#1A1A1C',
        border: `1px solid ${hover ? 'rgba(10, 132, 255, 0.35)' : 'rgba(235, 235, 245, 0.06)'}`,
        borderRadius: '12px',
        padding: '24px 24px 22px',
        cursor: 'pointer',
        fontFamily,
        color: '#EBEBF5',
        transition: 'all 0.15s ease',
        display: 'flex', flexDirection: 'column', minHeight: '200px',
      }}
    >
      <div style={{
        fontSize: '11px', textTransform: 'uppercase', letterSpacing: '1.5px',
        color: 'rgba(235, 235, 245, 0.45)', fontWeight: 600, marginBottom: '12px',
      }}>
        Example brief
      </div>
      <div style={{
        fontFamily: serif, fontSize: '20px', fontWeight: 500,
        letterSpacing: '-0.3px', color: '#EBEBF5', marginBottom: '10px',
        lineHeight: 1.25,
      }}>
        {demo.title}
      </div>
      <div style={{
        fontSize: '13px', color: 'rgba(235, 235, 245, 0.65)',
        lineHeight: 1.6, marginBottom: '16px', flex: 1,
      }}>
        {demo.teaser}
      </div>
      <div style={{
        display: 'flex', justifyContent: 'space-between', alignItems: 'center',
        marginTop: 'auto', paddingTop: '12px',
        borderTop: '1px solid rgba(235, 235, 245, 0.05)',
      }}>
        <div style={{ fontSize: '13px', color: 'rgba(235, 235, 245, 0.55)' }}>
          £{Number(demo.amount_in_dispute || 0).toLocaleString()} in dispute
        </div>
        <div style={{
          fontSize: '13px', fontWeight: 600,
          color: hover ? '#0A84FF' : 'rgba(10, 132, 255, 0.75)',
        }}>
          See the brief →
        </div>
      </div>
    </button>
  );
};

const TopBar = ({ onExit, onStart }) => (
  <div style={{
    position: 'sticky', top: 0, zIndex: 20,
    backgroundColor: 'rgba(15, 15, 16, 0.9)',
    backdropFilter: 'blur(12px)',
    borderBottom: '1px solid rgba(235, 235, 245, 0.06)',
    padding: '14px 28px',
    display: 'flex', alignItems: 'center', justifyContent: 'space-between',
  }}>
    <button
      onClick={onExit}
      style={{
        fontWeight: 700, fontSize: '14px', letterSpacing: '-0.3px',
        background: 'none', border: 'none', color: '#EBEBF5', cursor: 'pointer',
        fontFamily, padding: 0,
      }}
    >
      COURTLESS{' '}
      <span style={{ color: 'rgba(235, 235, 245, 0.5)', fontWeight: 400 }}>
        Disputes Without Courts
      </span>
    </button>
    <button
      onClick={onStart}
      style={{
        padding: '8px 16px', borderRadius: '6px',
        backgroundColor: 'transparent', color: '#EBEBF5',
        border: '1px solid rgba(235, 235, 245, 0.15)',
        fontSize: '12px', fontWeight: 500, cursor: 'pointer', fontFamily,
      }}
    >
      Start my audit →
    </button>
  </div>
);

export default DemoList;
